/** Local fleet image served from /public */
export const DEFAULT_CAR_IMAGE = '/car%20pic.jpeg'

export const heroImage = DEFAULT_CAR_IMAGE
export const aboutImage = DEFAULT_CAR_IMAGE

// Specific car images (matching files in /public)
export const MERCEDES_G_BRABUS_IMAGE = '/Mercedes%20G%20Wagon%20Brabus.jpeg'
export const BMW_I8_IMAGE = '/BMW%20i8.jpeg'
export const BMW_7_SERIES_IMAGE = '/BMW%207%20Series.jpeg'
export const BENTLEY_IMAGE = '/Bentley.jpeg'
export const LAMBORGHINI_URUS_IMAGE = '/Laborghini%20Urus.png'
export const GMC_LIMOUSINE_IMAGE = '/GMC%20Limousine.jpeg'
export const LEXUS_LIMOUSINE_IMAGE = '/Lexus%20Limousine.jpeg'
export const TUNDRA_LIMOUSINE_IMAGE = '/Tundra%20Limousine.jpeg'
export const MERCEDES_AMG_C_IMAGE = '/Mercedes%20AMG%20C%20Class.jpeg'
export const MERCEDES_MAYBACH_IMAGE = '/Mercedes%20Maybach%20S%20Class.jpeg'
export const PORSCHE_TAYCAN_IMAGE = '/Porsche%20Taycan.jpeg' 
export const RANGE_ROVER_VOGUE_IMAGE = '/Range%20Rover%20Vogue.jpeg'
export const TOYOTA_FORTUNER_IMAGE = '/Toyota%20Fortuner.jpeg'
export const TOYOTA_TUNDRA_IMAGE = '/Toyota%20Tundra.jpeg'
export const TOYOTA_LAND_CRUISER_ZX_IMAGE = '/Toyota%20Land%20Cruiser%20ZX%20V8.jpeg'
export const TOYOTA_LC300_IMAGE = '/Toyota%20LC300.jpeg'
export const TOYOTA_PRADO_TX_IMAGE = '/Toyota%20Prado%20TX.jpeg'
export const TOYOTA_REVO_IMAGE = '/Toyota%20Revo.jpeg'
export const TOYOTA_HIACE_HIGH_ROOF_IMAGE = '/Toyota%20Hiace%20High%20Roof.jpeg'
export const TOYOTA_GRANDE_IMAGE = '/Toyota%20Grande.jpeg'
export const TOYOTA_ALTIS_GLI_XLI_IMAGE = '/Toyota%20Altis%20GLI%20XLI.jpeg'
export const TOYOTA_YARIS_IMAGE = '/Toyota%20Yaris.jpeg'
export const AUDI_A6_IMAGE = '/Audi%20A6.jpeg'
export const HONDA_CIVIC_11_IMAGE = '/Honda%20Civic%2011th%20Gen.jpeg'
export const HONDA_CIVIC_X_IMAGE = '/Honda%20Civic%20X.jpeg'
export const HONDA_BRV_IMAGE = '/Honda%20BRV.jpeg'
export const SUZUKI_ALTO_IMAGE = '/Suzuki%20Alto.jpeg'
export const SUZUKI_WAGONR_IMAGE = '/Suzuki%20WagonR.jpeg'