/** Local fleet image served from /public */
export const DEFAULT_CAR_IMAGE = '/car%20pic.webp'

export const heroImage = DEFAULT_CAR_IMAGE

export const aboutImage = '/About%20Image.webp'

// Specific car images (matching files in /public)
export const MERCEDES_G_BRABUS_IMAGE = '/Mercedes%20G%20Wagon%20Brabus.webp'
export const BMW_I8_IMAGE = '/BMW%20i8.webp'
export const BMW_7_SERIES_IMAGE = '/BMW%207%20Series.webp'
export const BENTLEY_IMAGE = '/Bentley.webp'
export const LAMBORGHINI_URUS_IMAGE = '/Laborghini%20Urus.webp'
export const GMC_LIMOUSINE_IMAGE = '/GMC%20Limousine.webp'
export const LEXUS_LIMOUSINE_IMAGE = '/Lexus%20Limousine.webp'
export const TUNDRA_LIMOUSINE_IMAGE = '/Tundra%20Limousine.webp'
export const MERCEDES_AMG_C_IMAGE = '/Mercedes%20AMG%20C%20Class.webp'
export const MERCEDES_MAYBACH_IMAGE = '/Mercedes%20Maybach%20S%20Class.webp'
export const PORSCHE_TAYCAN_IMAGE = '/Porsche%20Taycan.webp' 
export const RANGE_ROVER_VOGUE_IMAGE = '/Range%20Rover%20Vogue.webp'
export const TOYOTA_FORTUNER_IMAGE = '/Toyota%20Fortuner.webp'
export const TOYOTA_TUNDRA_IMAGE = '/Toyota%20Tundra.webp'
export const TOYOTA_LAND_CRUISER_ZX_IMAGE = '/Toyota%20Land%20Cruiser%20ZX%20V8.webp'
export const TOYOTA_LC300_IMAGE = '/Toyota%20LC300.webp'
export const TOYOTA_PRADO_TX_IMAGE = '/Toyota%20Prado%20TX.webp'
export const TOYOTA_REVO_IMAGE = '/Toyota%20Revo.webp'
export const TOYOTA_HIACE_HIGH_ROOF_IMAGE = '/Toyota%20Hiace%20High%20Roof.webp'
export const TOYOTA_GRANDE_IMAGE = '/Toyota%20Grande.webp'
export const TOYOTA_ALTIS_GLI_XLI_IMAGE = '/Toyota%20Altis%20GLI%20XLI.webp'
export const TOYOTA_YARIS_IMAGE = '/Toyota%20Yaris.webp'
export const AUDI_A6_IMAGE = '/Audi%20A6.webp'
export const AUDI_A5_IMAGE = '/Audi%20A5.webp'
export const HONDA_CIVIC_11_IMAGE = '/Honda%20Civic%2011th%20Gen.webp'
export const HONDA_CIVIC_X_IMAGE = '/Honda%20Civic%20X.webp'
export const HONDA_BRV_IMAGE = '/Honda%20BRV.webp'
export const SUZUKI_ALTO_IMAGE = '/Suzuki%20Alto.webp'
export const SUZUKI_WAGONR_IMAGE = '/Suzuki%20WagonR.webp'
export const LEXUS_LX570_IMAGE = '/Lexus%20LX570.webp'
export const RANGE_ROVER_AUTOBIOGRAPHY_IMAGE = '/Range%20Rover%20Autobiograpghy.webp'
export const RANGE_ROVER_SVR_IMAGE = '/Range%20Rover%20SVR.webp'

// Package images (matching files in /public)
export const BARAT_PACKAGE_IMAGE = '/Barat%20Package.webp'
export const MEHNDI_PACKAGE_IMAGE = '/Mehndi%20Package.webp'
export const VIP_GROOM_ENTRY_IMAGE = '/VIP%20Groom%20Entry.webp'
export const FULL_WEDDING_TRANSPORT_IMAGE = '/Full%20Wedding%20Transport.webp'